include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_final_locals
    - prefer_single_quotes
    - unawaited_futures

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
  exclude:
    - build/**
    - android/**
    - ios/**
